export const cards = [
	{ img: 'https://picsum.photos/400/100', id: 1, title: 'ZAMANI URETKEN KULLANMA', date: '01 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 2, title: 'ZAMANI URETKEN KULLANMA', date: '02 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 3, title: 'ZAMANI URETKEN KULLANMA', date: '03 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 4, title: 'ZAMANI URETKEN KULLANMA', date: '04 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 5, title: 'ZAMANI URETKEN KULLANMA', date: '05 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 6, title: 'ZAMANI URETKEN KULLANMA', date: '06 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 7, title: 'ZAMANI URETKEN KULLANMA', date: '07 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 8, title: 'ZAMANI URETKEN KULLANMA', date: '08 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 9, title: 'ZAMANI URETKEN KULLANMA', date: '09 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 10, title: 'ZAMANI URETKEN KULLANMA', date: '10 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 11, title: 'ZAMANI URETKEN KULLANMA', date: '11 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 12, title: 'ZAMANI URETKEN KULLANMA', date: '12 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 13, title: 'ZAMANI URETKEN KULLANMA', date: '13 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 14, title: 'ZAMANI URETKEN KULLANMA', date: '14 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 15, title: 'ZAMANI URETKEN KULLANMA', date: '15 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 16, title: 'ZAMANI URETKEN KULLANMA', date: '16 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 17, title: 'ZAMANI URETKEN KULLANMA', date: '17 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' },
	{ img: 'https://picsum.photos/400/100', id: 18, title: 'ZAMANI URETKEN KULLANMA', date: '18 MART CUMA', activityTime: 'GEÇMİŞ ETKİNLİK', activity: 'ÇEVRİMİÇİ' }
];
