export const GET_ORGANISATOR_LIST_REQUEST = 'ORGANISATOR_LIST_REQUEST';
export const GET_ORGANISATOR_LIST_SUCCESS = 'ORGANISATOR_LIST_SUCCESS';
export const GET_ORGANISATOR_LIST_FAILURE = 'ORGANISATOR_LIST_FAILURE';

export const CREATE_ORGANISATOR_REQUEST = 'CREATE_ORGANISATOR_REQUEST';
export const CREATE_ORGANISATOR_SUCCESS = 'CREATE_ORGANISATOR_SUCCESS';
export const CREATE_ORGANISATOR_FAILURE = 'CREATE_ORGANISATOR_FAILURE';

export const REMOVE_ORGANISATOR_REQUEST = 'REMOVE_ORGANISATOR_REQUEST';
export const REMOVE_ORGANISATOR_SUCCESS = 'REMOVE_ORGANISATOR_SUCCESS';
export const REMOVE_ORGANISATOR_FAILURE = 'REMOVE_ORGANISATOR_FAILURE';

export const UPDATE_ORGANISATOR_REQUEST = 'UPDATE_ORGANISATOR_REQUEST';
export const UPDATE_ORGANISATOR_SUCCESS = 'UPDATE_ORGANISATOR_SUCCESS';
export const UPDATE_ORGANISATOR_FAILURE = 'UPDATE_ORGANISATOR_FAILURE';
